### DISCUSSION TITLE
Adding a new turbine

### DISCUSSION THREAD

**Discussion by moptis** [NatLabRockies/floris#479] [Q&A] [answered]
Hi FLORIS team,

When adding a new turbine to FLORIS, it appears that the turbine must be included in the repo's 'floris/turbine_library' folder in order to work. Is there a way to remove this requirement or specify an alternate path outside the repo where valid turbines are stored? Ideally I'd have a separate library independent of the FLORIS repo. 

Thanks!

![image](https://user-images.githubusercontent.com/32751681/182448680-657041ff-7bb7-493e-924a-1e3772f11390.png)

**Comment by bayc** [comment, marked as answer]
Yes! You can use the `!include` functionality in your input file to specify a path to a turbine definition file. Within the `farm` section of the input file, where `turbine_type` is specified, you would use `!include` like:

```
farm:
  layout_x:
  - 0.0
  layout_y:
  - 0.0
  turbine_type:
  - !include /path/to/turbine/definition/custom_turbine.yaml
```

Note, you need to specify the full file name, including the `.yaml`. Also, relative paths work, relative to where your input file is stored.
