### DISCUSSION TITLE
How to add turbine yaml file in turbine_library?

### DISCUSSION THREAD

**Discussion by jacktang** [NatLabRockies/floris#593] [Q&A] [answered]
Hello,

I want to add customized turbines in floris and calculate AEP for those turbines.
I found the turbine template definitions are in `turbine_library` dir, and here are my questions:

1. Is there any document to explain every field and the related values come from (such as `power_thrust_table`)? 
2. Is there anything else I missed in order to support different type turbine AEP calculation?

Thanks!

**Comment by rafmudaf** [comment, marked as answer]
Hi @jacktang,

We have not yet included a description of the turbine input file in the online documentation, so I've marked up one of the included turbine definitions below. @paulf81 @bayc please review and add information where needed.

```yaml
# Name to refer to this turbine. It should match the file name.
turbine_type: 'nrel_5MW'

# Generator loss model that would reduce the power produced
generator_efficiency: 1.0

# Cosine coefficient correlating yaw to power loss; see turbine.power()
pP: 1.88

# Not used
pT: 1.88

# Design hub height
hub_height: 90.0

# Design rotor diameter
rotor_diameter: 126.0

# Design tip speed ratio
TSR: 8.0

# Reference density where the power / thrust table is defined; typically
# the same as flow_field.air_density in the primary input file
ref_density_cp_ct: 1.225

# Performance table; power vs wind speed and thrust vs wind speed
# Here, I've removed many of the points for brevity, but you can see the idea.
power_thrust_table:

  # Power for each given wind speed
  power:
    - 0.0
    - 0.406059
    - 0.435903
    - 0.193981
    - 0.081836
    - 0.041900

  # Thrust force for each given wind speed
  thrust:
    - 0.0
    - 0.89210543
    - 0.75232027
    - 0.24361964
    - 0.10339901
    - 0.05741999

  # Wind speeds for the power and thrust entries above
  wind_speed:
    - 0.0
    - 5.0
    - 10.0
    - 15.0
    - 20.0
    - 25.0
```

We recently added a feature to support defining an external turbine library. See #568 for a description of the new feature and how to use it.
