### DISCUSSION TITLE
Velocity profiles in Floris

### DISCUSSION THREAD

**Discussion by fwasilczuk** [NatLabRockies/floris#626] [Q&A] [answered]
Hi, 
I stumbled upon an incosistent code behaviour when calculating the velocity profiles.
I'm trying to investigate the impact of rotor averaging on the accuracy of simulations. 
When changing the number of rotor points I can see the averaged rotor valocity changing, which results in the change of power and Ct (which is expected).
But when I'm comparing the velocity profiles there is no difference between cases with different number of points (which seems not consistent with the previous point).
I tried to investigate, by dumping the Ct from axial_induction function in /simulations/turbine library. My code (below) does "calculate_wake", where the axial induction function is called once, returning different values for different number of averaging points.
When "calculate_cross_plane" is used later, the axial induction is called three times. First two calls return the same Ct values for cases with different number of rotor averaging points. Only the last call returns the same values as for "calculate_wake", which are different for different number of rotor points. Maybe this has to do something with the fact that the velocity profiles don't differ from each other?
Can someone explain this code behaviour? Or maybe I'm doing something wrong?
Regards
Filip

Minimal working example:

```
import matplotlib.pyplot as plt
from floris.tools import FlorisInterface

def traverse(input_file="setup_file.yml", grid_points=1):
    fi = FlorisInterface(input_file)

    solver_settings = {
      "type": "turbine_grid",
      "turbine_grid_points": grid_points
    }

    fi.reinitialize(solver_settings=solver_settings)
    fi.calculate_wake()
    cross_plane = fi.calculate_cross_plane(y_resolution=3, z_resolution=41, z_bounds = (0, 400), downstream_dist=400)
    plane_values = cross_plane.df
    traverse = plane_values[(plane_values['x1'] == 0)][["x2", "u", "v", "w"]]
    power_turbine1=fi.get_turbine_powers()[0,0,0]/1000
    ct1=(fi.get_turbine_Cts())[0,0,0]
    WS_eff1=fi.get_turbine_average_velocities()[0,0,0]   

    return WS_eff1, power_turbine1, ct1, traverse 

point1=traverse(grid_points=1)
points49=traverse(grid_points=49)

print("Rotor average velocity: 1 point - %s m/s, 49 points - %s m/s" % (point1[0], points49[0]))
print("Power: 1 point - %s kW, 49 points - %s kW" % (point1[1], points49[1]))
print("Ct: 1 point - %s, 49 points - %s" % (point1[2], points49[2]))

plt.figure()
plt.plot(point1[3]['u'], point1[3]['x2'], label='1 point') 
plt.plot(points49[3]['u'], point1[3]['x2'], label='49 points', linestyle="--") 
plt.legend()
plt.show()
```
Setup_file:

```
name: GCH
description: Three turbines using Gauss Curl Hybrid model
floris_version: v3.0.0

logging:
  console:
    enable: true
    level: WARNING
  file:
    enable: false
    level: WARNING

solver:
  type: turbine_grid
  turbine_grid_points: 3

farm:
  layout_x:
  - 0.0
  layout_y:
  - 0.0
  turbine_type:
  - iea_10MW

flow_field:
  air_density: 1.225
  reference_wind_height: -1
  turbulence_intensity: 0.06
  wind_directions:
  - 270.0
  wind_shear: 0.12
  wind_speeds:
  - 10
  wind_veer: 0.0

wake:
  model_strings:
    combination_model: sosfs
    deflection_model: jimenez
    turbulence_model: none
    velocity_model: jensen

  enable_secondary_steering: true
  enable_yaw_added_recovery: true
  enable_transverse_velocities: true

  wake_deflection_parameters:
    gauss:
      ad: 0.0
      alpha: 0.58
      bd: 0.0
      beta: 0.077
      dm: 1.0
      ka: 0.38
      kb: 0.004
    jimenez:
      ad: 0.0
      bd: 0.0
      kd: 0.1

  wake_velocity_parameters:
    cc:
      a_s: 0.179367259
      b_s: 0.0118889215
      c_s1: 0.0563691592
      c_s2: 0.13290157
      a_f: 3.11
      b_f: -0.68
      c_f: 2.41
      alpha_mod: 1.0
    gauss:
      alpha: 0.58
      beta: 0.077
      ka: 0.38
      kb: 0.004
    jensen:
      we: 0.1

  wake_turbulence_parameters:
    crespo_hernandez:
      initial: 0.1
      constant: 0.5
      ai: 0.8
      downstream: -0.32
```
