### DISCUSSION TITLE
Input array formats

### DISCUSSION THREAD

**Discussion by rafmudaf** [NatLabRockies/floris#794] [v4 Design Discussion]
FLORIS has a pattern of allowing an input array of size 1 be expanded to the full problem size with all elements equal to the single value give. For example, the following input where wind direction and wind speed are length 2 and turbulence intensity is length 1 is allowed:
```yaml
wind_direction:
- 270
- 270
wind_speed:
- 8
- 9
turbulence_intensity:
- 0.1
```
Internally, FLORIS expands turbulence intensity to the same length as wind direction and wind speed and applies `0.1` to all elements. In https://github.com/NREL/floris/pull/793, the question is asked whether this pattern should apply to any array-type inputs.

In earlier versions of FLORIS, the wind directions and wind speeds were central to the problem statement of a FLORIS calculation. However, in FLORIS v4, more aspects of the problem statement are as important, and the central property is now `findex`. Previously, I would have said that explicitly defining all wind directions and wind speeds is a requirements, but with the new structure I don't think this holds.

## UI Evaluation

So how would the input data look if we allow for any array inputs to be either 1 or `n_findex`?
Here are some examples:
```yaml
# n_findex = 2
wind_direction:
- 270
wind_speed:
- 8
- 9
turbulence_intensity:
- 0.1

# n_findex = 1
wind_direction:
- 270
wind_speed:
- 8
turbulence_intensity:
- 0.1

# n_findex = 2
wind_direction:
- 270
wind_speed:
- 8
turbulence_intensity:
- 0.1
- 0.2
```

**Comment by misi9170** [comment]
To me, broadcasting up would make more sense if the variable to be broadcasted was actually a scalar, rather than a length 1 list/array. As I see it, the broadcasting is clearer with `fi.reinitialize(wind_directions=270.0, wind_speeds=[6.0, 8.0, 10.0])` than `fi.reinitialize(wind_directions=[270.0], wind_speeds=[6.0, 8.0, 10.0])`. This would require an extra step in the handling to check if the arguments passed have attribute `len`.

**Reply by paulf81** [reply]
I like that

**Reply by rafmudaf** [reply]
Ah that's a good point. The yaml form is:
```yaml
wind_directions: 270
wind_speeds:
- 8
- 9
turbulence_intensities: 0.1
```
