### DISCUSSION TITLE
flow_field_grid Solver

### DISCUSSION THREAD

**Discussion by Jlewis17** [NatLabRockies/floris#898] [Q&A]
I am trying to use the flow_field_grid solver to be able to extract the entire flow feild behind a singke turbine. So far all I can find is the discussion in #738 but following that I get error: 
"xmin = min(x[0,0]) - 2 * self.turbine_diameters
TypeError: 'numpy.float64' object is not iterable"

1) How do I solve this error?
2) How should the solver section in my input .yaml file look like if I want to use the flow_field_grid solver?

 Any help would be greatly appreciated.

**Comment by rafmudaf** [comment]
Hi @Jlewis17 thanks for the question. I'll need more information to understand what you've tried and why you're running into an error. Which version of FLORIS are you using? Also, please include your script and the relevant portions of the input file. You can format it easily with [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to improve readability.

**Comment by Jlewis17** [comment]
Hi @rafmudaf I am currently using V4 of Floris. I have created lots of different input turbine files, based on real life turbines, and I am trying to create a custom input .yaml file for each turbine; in order to extract data regarding the full wake expansion for each turbine.  Reading #738 my understading would be to use the flow_field_grid solver to achieve this goal but I am unsure how properly use this function. Currently my custom input .yaml file looks like this:

```
name: GCH GCH Turbine 1
description: Turbines using Gauss Curl Hybrid model
floris_version: v4

logging:
  console:
    enable: true
    level: WARNING
  file:
    enable: false
    level: WARNING

solver:
  type: flow_field_grid
  flow_field_grid_points:
  - 200  # number of points in the x direction 
  - 100  # number of points in the y direction
  - 50   # number of points in the z direction

farm:
  layout_x:
  - 0.0
  layout_y:
  - 0.0
  turbine_type:
  - turbine_1



flow_field:
  air_density: 1.225
  reference_wind_height: -1
  turbulence_intensities:
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  wind_directions:
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  - 270.0
  wind_shear: 0.12
  wind_speeds:
  - 0.0
  - 0.5
  - 1.0
  - 1.5
  - 2.0
  - 2.5
  - 3.0
  - 3.5
  - 4.0
  - 4.5
  - 5.0
  - 5.5
  - 6.0
  - 6.5
  - 7.0
  - 7.5
  - 8.0
  - 8.5
  - 9.0
  - 9.5
  - 10.0
  - 10.5
  - 11.0
  - 11.5
  - 12.5
  - 13.0
  - 13.5
  - 14.0
  - 14.5
  - 15.0
  - 15.5
  - 16.0
  - 16.5
  - 17.0
  - 17.5
  - 18.0
  - 18.5
  - 19.0
  - 19.5
  - 20.0
  - 20.5
  - 21.0
  - 21.5
  - 22.0
  - 22.5
  - 23.0
  - 23.5
  - 24.0
  - 24.5
  - 25.0
  - 25.5
  - 26.0
  - 26.5
  - 27.0
  - 27.5
  - 28.0
  - 28.5
  - 29.0
  - 29.5
  - 30.0
  - 30.5
  - 31.0
  - 31.5
  - 32.0
  - 32.5
  - 33.0
  - 33.5
  - 34.0
  - 34.5
  - 35.0
  
  wind_veer: 0.0

wake:
  model_strings:
    combination_model: sosfs
    deflection_model: gauss
    turbulence_model: crespo_hernandez
    velocity_model: gauss

  enable_secondary_steering: false
  enable_yaw_added_recovery: false
  enable_transverse_velocities: false
  enable_active_wake_mixing: false

  wake_deflection_parameters:
    gauss:
      ad: 0.0
      alpha: 0.58
      bd: 0.0
      beta: 0.077
      dm: 1.0
      ka: 0.38
      kb: 0.004
    jimenez:
      ad: 0.0
      bd: 0.0
      kd: 0.05

  wake_velocity_parameters:
    cc:
      a_s: 0.179367259
      b_s: 0.0118889215
      c_s1: 0.0563691592
      c_s2: 0.13290157
      a_f: 3.11
      b_f: -0.68
      c_f: 2.41
      alpha_mod: 1.0
    gauss:
      alpha: 0.58
      beta: 0.077
      ka: 0.38
      kb: 0.004
    jensen:
      we: 0.05

  wake_turbulence_parameters:
    crespo_hernandez:
      initial: 0.1
      constant: 0.5
      ai: 0.8
      downstream: -0.32
```
